config/routes.rb
Rails.application.routes.draw do

    match 'user/create' => "user#create", :via => :get
    get 'user/:macaddress' => 'user#show'
    get 'user/' =>"user#index"

    match 'smart_point/create' => "smart_point#create", :via => :get
    get 'smart_point/' => "smart_point#index"
    get 'smart_point/:macaddress' => 'smart_point#show'

    match 'user_smart_points/' => "user_smart_points#create", :via => :get
    get 'user_smart_points/' => "user_smart_points#index"

   root 'user_smart_points#maps'

end

app/models/smart_point.rb
class SmartPoint < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/user_smart_point.rb
class UserSmartPoint < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/smart_point_controller.rb
class SmartPointController < ApplicationController
  respond_to :json
  skip_before_action :verify_authenticity_token

  # GET /users.json
  def index
    @sp = SmartPoint.all
    render json: @sp
  end
 def show
 	@sp = SmartPoint.find_by(macaddress: params[:macaddress])
    render json: @sp
 end
  # POST /users.json
 def create
    if SmartPoint.exists?(:macaddress => params[:macaddress])
      UserSmartPoint.create(:user_mac => params[:user_mac], :spoint_mac =>params[:macaddress], :date => DateTime.now)
    else
        @sp = SmartPoint.new()
        @sp.macaddress= params[:macaddress]
        @sp.name= params[:name]
        @sp.lat= params[:lat]
        @sp.long= params[:long]
        if @sp.save
          UserSmartPoint.create(:user_mac => params[:user_mac], :spoint_mac =>params[:macaddress], :date => DateTime.now)
          render json: {'status': 'success punto y user punto'}
        #  else 
         #   render json: {'status':'error', 'errors':@user.errors}
          #end
        else
          render json: {'status':'error', 'errors':@user.errors}
        end
    end
  end
  def new
  	@sp=SmartPoint.new
  end 


end

app/controllers/user_controller.rb
class UserController < ApplicationController
respond_to :json
   skip_before_action :verify_authenticity_token

  # GET /users.json
  def index
    @users = User.all
    render json: @users
  end
 def show
 	    @user = User.find_by(macaddress: params[:macaddress])
    	render json: @user
  end
  # GET /users.json
 def create
    if User.exists?(:macaddress => params[:macaddress])
      render json: {'status': 'same'}
    else
       @user = User.new()
       @user.macaddress=params[:macaddress]
       if @user.save
      render json: {'status': 'success'}
       else
       render json: {'status':'error', 'errors':@user.errors}
       end
    end
  end
  def new
  	@user=User.new
  end 
  # PATCH/PUT /users/1.json
  def update
   if @user.update(user_params)
    respond_with({'status':'success'})
   else
    respond_with({'status':'error'})
   end
  end


  # DELETE /users/1.json
  def destroy
   @user.destroy
   respond_with({'status':'User deleted'})
  end
 
  def user_params
   params.require(:macaddress)
  end

end

app/controllers/user_smart_points_controller.rb
class UserSmartPointsController < ApplicationController
  before_action :set_user_smart_point, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token


  # GET /user_smart_points
  # GET /user_smart_points.json
  def index
    @user_smart_points = UserSmartPoint.all
    render json: @user_smart_points
  end

  # GET /user_smart_points/1
  # GET /user_smart_points/1.json
  def show

  end
  def maps
    if (User.exists?())
        user = User.first.macaddress
        @spmacs=UserSmartPoint.where(user_mac: user).collect{|x| x.spoint_mac}
        @points=SmartPoint.where(macaddress: @spmacs)
        @hash = Gmaps4rails.build_markers(@points) do |point, marker|
          marker.lat point.lat
          marker.lng point.long
          marker.infowindow point.name
        end
    else
      render text: "No hay usuarios cargados"
    end
  end

  # GET /user_smart_points/new
  def new
    @user_smart_point = UserSmartPoint.new
  end

  # GET /user_smart_points/1/edit
  def edit
  end

  # POST /user_smart_points
  # POST /user_smart_points.json
  def create
    @user_smart_point = UserSmartPoint.new(user_smart_point_params)

    respond_to do |format|
      if @user_smart_point.save
        format.html { redirect_to @user_smart_point, notice: 'User smart point was successfully created.' }
        format.json { render :show, status: :created, location: @user_smart_point }
      else
        format.html { render :new }
        format.json { render json: @user_smart_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_smart_points/1
  # PATCH/PUT /user_smart_points/1.json
  def update
    respond_to do |format|
      if @user_smart_point.update(user_smart_point_params)
        format.html { redirect_to @user_smart_point, notice: 'User smart point was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_smart_point }
      else
        format.html { render :edit }
        format.json { render json: @user_smart_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_smart_points/1
  # DELETE /user_smart_points/1.json
  def destroy
    @user_smart_point.destroy
    respond_to do |format|
      format.html { redirect_to user_smart_points_url, notice: 'User smart point was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_smart_point
      @user_smart_point = UserSmartPoint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_smart_point_params
      params.require(:user_smart_point).permit(:user_mac, :spoint_mac, :date)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/smart_point_helper.rb
module SmartPointHelper
end

app/helpers/user_controller_helper.rb
module UserControllerHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/user_smart_points_helper.rb
module UserSmartPointsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ServerBlindApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/smart_point/create.html.erb
<%= params.to_json %>

app/views/smart_point/new.html.erb
<%= form_for :smart_point, :url => { :action => :create } do |f| %>
  <p>
    <%= f.label :macaddress %><br>
    <%= f.text_field :macaddress %>
  </p>
<p>
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </p><p>
    <%= f.label :long %><br>
    <%= f.text_field :long %>
  </p><p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :user_mac %><br>
    <%= f.text_field :user_mac %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/user/new.html.erb
<%= form_for :user, :url => { :action => :create } do |f| %>
  <p>
    <%= f.label :macaddress %><br>
    <%= f.text_field :macaddress %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/user_smart_points/_form.html.erb
<%= form_for(@user_smart_point) do |f| %>
  <% if @user_smart_point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_smart_point.errors.count, "error") %> prohibited this user_smart_point from being saved:</h2>

      <ul>
      <% @user_smart_point.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_mac %><br>
    <%= f.text_field :user_mac %>
  </div>
  <div class="field">
    <%= f.label :spoint_mac %><br>
    <%= f.text_field :spoint_mac %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_smart_points/edit.html.erb
<h1>Editing User Smart Point</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_smart_point %> |
<%= link_to 'Back', user_smart_points_path %>

app/views/user_smart_points/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Smart Points</h1>

<table>
  <thead>
    <tr>
      <th>User mac</th>
      <th>Spoint mac</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_smart_points.each do |user_smart_point| %>
      <tr>
        <td><%= user_smart_point.user_mac %></td>
        <td><%= user_smart_point.spoint_mac %></td>
        <td><%= user_smart_point.date %></td>
        <td><%= link_to 'Show', user_smart_point %></td>
        <td><%= link_to 'Edit', edit_user_smart_point_path(user_smart_point) %></td>
        <td><%= link_to 'Destroy', user_smart_point, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User smart point', new_user_smart_point_path %>

app/views/user_smart_points/maps.html.erb
<div style='width: 100%;'>
  <div id="map" style='width: 100%; height: 500px;'></div>
</div>

<script src="//maps.google.com/maps/api/js?key=AIzaSyB_Yl5RTkqK3Mdh8BMxk9IJAroCnaws6hw"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
<script>handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){ 
markers = handler.addMarkers(<%=raw @hash.to_json %>);

  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  });

</script>

app/views/user_smart_points/new.html.erb
<h1>New User Smart Point</h1>

<%= render 'form' %>

<%= link_to 'Back', user_smart_points_path %>

app/views/user_smart_points/show.html.erb
<div style='width: 100%;'>
  <div id="map" style='width: 100%; height: 500px;'></div>
</div>

<script src="//maps.google.com/maps/api/js?key=AIzaSyB_Yl5RTkqK3Mdh8BMxk9IJAroCnaws6hw"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
<script>handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){ 
markers = handler.addMarkers(<%=raw @hash.to_json %>);

  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  });

</script>